/**
 * Icon re-exports from @tabler/icons-react.
 * Import from here (not directly from the library) so we keep a single
 * controlled surface — easier to swap the underlying library later.
 *
 * Add new icons as needed: find the name at https://tabler.io/icons
 */
export {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRightCircle,
  IconArchive,
  IconBike,
  IconBus,
  IconCar,
  IconCircleMinus,
  IconCoffee,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconBed,
  IconBookmark,
  IconBug,
  IconBulb,
  IconCalendarTime,
  IconCheck,
  IconCheckbox,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCategory,
  IconCircleDashed,
  IconCircleCheck,
  IconCoin,
  IconDatabase,
  IconDeviceFloppy,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconGripVertical,
  IconHeart,
  IconHourglass,
  IconKey,
  IconLink,
  IconList,
  IconLoader2,
  IconMap,
  IconMapPin,
  IconMapSearch,
  IconMessage,
  IconMessageReport,
  IconNotes,
  IconPencil,
  IconPlayerPlay,
  IconPlayerStop,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSend,
  IconSoup,
  IconSparkles,
  IconStar,
  IconTestPipe,
  IconThumbUp,
  IconTools,
  IconTrash,
  IconTrain,
  IconTree,
  IconUpload,
  IconWalk,
  IconWorld,
  IconX,
} from "@tabler/icons-react";

export type { IconProps } from "@tabler/icons-react";
